In [1]:
from fastai.collab import *
from fastai.tabular.all import *

In [2]:
path = untar_data(URLs.ML_100k)

In [3]:
path.ls()

(#23) [Path('/home/anasys/.fastai/data/ml-100k/u4.test'),Path('/home/anasys/.fastai/data/ml-100k/u5.base'),Path('/home/anasys/.fastai/data/ml-100k/u3.base'),Path('/home/anasys/.fastai/data/ml-100k/u.info'),Path('/home/anasys/.fastai/data/ml-100k/u.data'),Path('/home/anasys/.fastai/data/ml-100k/ub.test'),Path('/home/anasys/.fastai/data/ml-100k/u.genre'),Path('/home/anasys/.fastai/data/ml-100k/allbut.pl'),Path('/home/anasys/.fastai/data/ml-100k/u1.base'),Path('/home/anasys/.fastai/data/ml-100k/u3.test')...]

In [4]:
ratings = pd.read_csv(path / 'u.data',
                      delimiter='\t',
                      header=None,
                      names=['user', 'movie', 'rating', 'timestamp'])

In [5]:
ratings.head()

user  movie  rating  timestamp
0   196    242       3  881250949
1   186    302       3  891717742
2    22    377       1  878887116
3   244     51       2  880606923
4   166    346       1  886397596

In [8]:
# science-fiction, action, old movies
last_skywalker = np.array([0.98, 0.9, -0.9])
casablanca = np.array([-0.99, -0.3, 0.8])

In [9]:
user1 = np.array([0.9, 0.8, -0.6])

In [10]:
(user1 * last_skywalker).sum()

2.1420000000000003

In [11]:
(user1 * casablanca).sum()

-1.611

In [12]:
movies = pd.read_csv(path / 'u.item',
                     delimiter='|',
                     encoding='latin-1',
                     usecols=(0, 1),
                     names=('movie', 'title'),
                     header=None)
movies.head()

movie              title
0      1   Toy Story (1995)
1      2   GoldenEye (1995)
2      3  Four Rooms (1995)
3      4  Get Shorty (1995)
4      5     Copycat (1995)

In [13]:
ratings = ratings.merge(movies)
ratings.head()

user  movie  rating  timestamp         title
0   196    242       3  881250949  Kolya (1996)
1    63    242       3  875747190  Kolya (1996)
2   226    242       5  883888671  Kolya (1996)
3   154    242       3  879138235  Kolya (1996)
4   306    242       5  876503793  Kolya (1996)

In [14]:
dls = CollabDataLoaders.from_df(ratings, item_name='title', bs=64)
dls.show_batch()

In [15]:
n_users = len(dls.classes['user'])
n_users

944

In [16]:
n_movies = len(dls.classes['title'])
n_movies

1665

In [17]:
n_factors = 5

In [18]:
user_factors = torch.randn(n_users, n_factors)
user_factors.shape

torch.Size([944, 5])

In [34]:
movie_factors = torch.randn(n_movies, n_factors)
movie_factors.shape

torch.Size([1665, 5])

In [44]:
one_hot_3 = one_hot(3, n_users).float()
user_factors.t() @ one_hot_3

tensor([ 0.4899, -0.2355, -0.0463,  0.9462,  0.5654])

In [46]:
user_factors.shape, one_hot_3.shape

(torch.Size([944, 5]), torch.Size([944]))

In [41]:
user_factors[3]

tensor([ 0.4899, -0.2355, -0.0463,  0.9462,  0.5654])

In [48]:
class Example:
    def __init__(self, a):
        self.a = a
    
    def say(self, x):
        return f'Hello {self.a}, {x}.'

In [49]:
ex = Example('Sylvan')
ex.say('nice to meet you')

'Hello Sylvan, nice to meet you.'

In [81]:
class DotProduct(Module):
    def __init__(self, n_users, n_movies, n_factors):
        self.user_factors = Embedding(n_users, n_factors)
        self.movie_factors = Embedding(n_movies, n_factors)
    
    def forward(self, x):
        # x[batch, 0] => user_id
        # x[batch, 1] => movie_id
        users = self.user_factors(x[:, 0])
        movies = self.movie_factors(x[:, 1])
        return (users * movies).sum(dim=1)

In [82]:
x, y = dls.one_batch()
x.shape, y.shape

(torch.Size([64, 2]), torch.Size([64, 1]))

In [83]:
x[:, 0].shape

torch.Size([64])

In [84]:
x[:, 1].shape

torch.Size([64])

In [85]:
user_factors = Embedding(n_users, n_factors)
users = user_factors(to_cpu(x[:, 0]))
users.shape

torch.Size([64, 5])

In [86]:
movie_factors = Embedding(n_movies, n_factors)
movies = movie_factors(to_cpu(x[:, 1]))
movies.shape

torch.Size([64, 5])

In [87]:
(users * movies).sum(dim=1).shape

torch.Size([64])

In [88]:
model = DotProduct(n_users, n_movies, 50)
model

DotProduct(
  (user_factors): Embedding(944, 50)
  (movie_factors): Embedding(1665, 50)
)

In [89]:
learn = Learner(dls, model, loss_func=MSELossFlat())

In [90]:
learn.fit_one_cycle(5, 5e-3)

In [91]:
class DotProduct(Module):
    def __init__(self, n_users, n_movies, n_factors, y_range=(0, 5.5)):
        self.user_factors = Embedding(n_users, n_factors)
        self.movie_factors = Embedding(n_movies, n_factors)
        self.y_range = y_range
    
    def forward(self, x):
        # x[batch, 0] => user_id
        # x[batch, 1] => movie_id
        users = self.user_factors(x[:, 0])
        movies = self.movie_factors(x[:, 1])
        return sigmoid_range((users * movies).sum(dim=1), *self.y_range)

In [92]:
model = DotProduct(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3)

In [93]:
class DotProduct(Module):
    def __init__(self, n_users, n_movies, n_factors, y_range=(0, 5.5)):
        self.user_factors = Embedding(n_users, n_factors)
        self.user_bias = Embedding(n_users, 1)

        self.movie_factors = Embedding(n_movies, n_factors)
        self.movie_bias = Embedding(n_movies, 1)

        self.y_range = y_range
    
    def forward(self, x):
        # x[batch, 0] => user_id
        # x[batch, 1] => movie_id
        users = self.user_factors(x[:, 0])
        movies = self.movie_factors(x[:, 1])
        res = (users * movies).sum(dim=1, keepdim=True)
        res += self.user_bias(x[:, 0]) + self.movie_bias(x[:, 1])
        return sigmoid_range(res, *self.y_range)

In [94]:
model = DotProduct(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3)

In [122]:
model = DotProduct(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3, wd=0.1)

In [96]:
class T(Module):
    def __init__(self):
        self.a = torch.ones(3)

In [99]:
L(T().parameters())

(#0) []

In [100]:
class T(Module):
    def __init__(self):
        self.a = nn.Parameter(torch.ones(3))

In [101]:
L(T().parameters())

(#1) [Parameter containing:
tensor([1., 1., 1.], requires_grad=True)]

In [102]:
class T(Module):
    def __init__(self):
        self.a = nn.Linear(1, 3, bias=False)

In [104]:
t = T()
L(t.parameters())

(#1) [Parameter containing:
tensor([[-0.8586],
        [ 0.8295],
        [-0.7262]], requires_grad=True)]

In [105]:
type(t.a.weight)

torch.nn.parameter.Parameter

In [106]:
def create_params(size):
    return nn.Parameter(torch.zeros(*size).normal_(0, 0.01))

In [110]:
create_params([3, 5]).shape

torch.Size([3, 5])

In [125]:
class DotProductBias(Module):
    def __init__(self, n_users, n_movies, n_factors, y_range=(0, 5.5)):
        self.user_factors = create_params([n_users, n_factors])
        self.user_bias = create_params([n_users])

        self.movie_factors = create_params([n_movies, n_factors])
        self.movie_bias = create_params([n_movies])

        self.y_range = y_range
    
    def forward(self, x):
        # x[batch, 0] => user_id
        # x[batch, 1] => movie_id
        users = self.user_factors[x[:, 0]]
        movies = self.movie_factors[x[:, 1]]
        res = (users * movies).sum(dim=1)
        res += self.user_bias[x[:, 0]] + self.movie_bias[x[:, 1]]                                                         
        return sigmoid_range(res, *self.y_range)

In [126]:
model = DotProductBias(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3, wd=0.1)

In [127]:
movie_bias = learn.model.movie_bias.squeeze()
movie_bias.shape

torch.Size([1665])

In [130]:
idxs = movie_bias.argsort()[:5]
idxs

tensor([ 295,  850, 1001,  561,  140], device='cuda:0')

In [131]:
movie_bias[idxs]

tensor([-0.3588, -0.3142, -0.2913, -0.2910, -0.2799], device='cuda:0',
       grad_fn=<IndexBackward>)

In [133]:
[dls.classes['title'][i] for i in idxs]

['Children of the Corn: The Gathering (1996)',
 'Lawnmower Man 2: Beyond Cyberspace (1996)',
 'Mortal Kombat: Annihilation (1997)',
 'Free Willy 3: The Rescue (1997)',
 'Beautician and the Beast, The (1997)']

In [134]:
idxs = movie_bias.argsort(descending=True)[:5]
idxs

tensor([1399, 1501,   99, 1282, 1318], device='cuda:0')

In [135]:
movie_bias[idxs]

tensor([0.5826, 0.5511, 0.5257, 0.5125, 0.4976], device='cuda:0',
       grad_fn=<IndexBackward>)

In [136]:
[dls.classes['title'][i] for i in idxs]

['Star Wars (1977)',
 'Titanic (1997)',
 'As Good As It Gets (1997)',
 "Schindler's List (1993)",
 'Shawshank Redemption, The (1994)']

## Using fastai.collab

In [19]:
learn = collab_learner(dls, n_factors=50, y_range=(0, 5.5))
learn.fit_one_cycle(5, 5e-3, wd=0.1)

In [20]:
learn.model

EmbeddingDotBias(
  (u_weight): Embedding(944, 50)
  (i_weight): Embedding(1665, 50)
  (u_bias): Embedding(944, 1)
  (i_bias): Embedding(1665, 1)
)

In [21]:
movie_bias = learn.model.i_bias.weight.squeeze()
movie_bias.shape

torch.Size([1665])

In [22]:
idxs = movie_bias.argsort(descending=True)[:5]
[dls.classes['title'][i] for i in idxs]

['Titanic (1997)',
 "Schindler's List (1993)",
 'Star Wars (1977)',
 'Silence of the Lambs, The (1991)',
 'Shawshank Redemption, The (1994)']

In [23]:
movie_factors = learn.model.i_weight.weight
movie_factors.shape

torch.Size([1665, 50])

In [24]:
idx = dls.classes['title'].o2i['Silence of the Lambs, The (1991)']
idx

1330

In [25]:
movie_factors[idx][None].shape

torch.Size([1, 50])

In [26]:
distances = nn.CosineSimilarity(dim=1)(movie_factors, movie_factors[idx][None])
distances.shape

torch.Size([1665])

In [27]:
idxs = distances.argsort(descending=True)[:10]
[dls.classes['title'][i] for i in idxs]

['Silence of the Lambs, The (1991)',
 'Traveller (1997)',
 'As Good As It Gets (1997)',
 'Shawshank Redemption, The (1994)',
 'Glory (1989)',
 'Last Time I Saw Paris, The (1954)',
 'When We Were Kings (1996)',
 'Alice in Wonderland (1951)',
 'Casablanca (1942)',
 'Love in the Afternoon (1957)']

## Deep Learning for Collaborative Filtering

In [31]:
embs = get_emb_sz(dls)
embs

[(944, 74), (1665, 102)]

In [35]:
class CollabNN(Module):
    def __init__(self, user_sz, item_sz, y_range=(0, 5.5), n_act=100):
        self.user_factors = Embedding(*user_sz)
        self.item_factors = Embedding(*item_sz)
        self.layers = nn.Sequential(
            nn.Linear(user_sz[1] + item_sz[1], n_act),
            nn.ReLU(),
            nn.Linear(n_act, 1))
        self.y_range = y_range
    
    def forward(self, x):
        embs = self.user_factors(x[:, 0]), self.item_factors(x[:, 1])
        x = self.layers(torch.cat(embs, dim=1))
        return sigmoid_range(x, *self.y_range)

In [38]:
model = CollabNN(*embs)
model

CollabNN(
  (user_factors): Embedding(944, 74)
  (item_factors): Embedding(1665, 102)
  (layers): Sequential(
    (0): Linear(in_features=176, out_features=100, bias=True)
    (1): ReLU()
    (2): Linear(in_features=100, out_features=1, bias=True)
  )
)

In [41]:
batch = dls.one_batch()
batch[0].shape, batch[1].shape

(torch.Size([64, 2]), torch.Size([64, 1]))

In [44]:
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3, wd=0.01)

In [46]:
learn = collab_learner(dls, use_nn=True, y_range=(0, 5.5), layers=[100, 50])
learn.fit_one_cycle(5, 5e-3, wd=0.1)